CustomLayout property can be writed.
MicrosoftDocs/VBA-Docs pull request #1380
Opened 2021-05-24 17:30 UTC by patternplane

2021-05-24 17:33 UTC, opbld31 commented
Docs Build status updates of commit _[3a18603](https://github.com/patternplane/VBA-Docs/commits/3a186034ece7e57c229ef18b979432dcdd72355e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/PowerPoint.Slide.CustomLayout.md](https://github.com/patternplane/VBA-Docs/blob/patch-1/api/PowerPoint.Slide.CustomLayout.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/office/vba/api/powerpoint.slide.customlayout?branch=pr-en-us-1380) | [Details](#user-content-d1ecb0843cacc5663ad145c368a0fea2-a566f24b)

<a id="d1ecb0843cacc5663ad145c368a0fea2-a566f24b"></a>
### [api/PowerPoint.Slide.CustomLayout.md](https://github.com/patternplane/VBA-Docs/blob/patch-1/api/PowerPoint.Slide.CustomLayout.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C24%5C6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d%5CPullRequest%5C202105241730260838-1380%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dK09C2ED6N58lR38lcOofXigLypgzo1leaIBrVsltJ4%3D&st=2021-05-24T17%3A28%3A55Z&se=2021-06-24T17%3A33%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 07:56 UTC, patternplane commented
Change the property of CustomLayout object
"Read-only" -> "Read/Write"

2021-05-27 08:01 UTC, opbld32 commented
Docs Build status updates of commit _[3a18603](https://github.com/patternplane/VBA-Docs/commits/3a186034ece7e57c229ef18b979432dcdd72355e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/PowerPoint.Slide.CustomLayout.md](https://github.com/patternplane/VBA-Docs/blob/patch-1/api/PowerPoint.Slide.CustomLayout.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/office/vba/api/powerpoint.slide.customlayout?branch=pr-en-us-1380) | [Details](#user-content-d1ecb0843cacc5663ad145c368a0fea2-31836886)

<a id="d1ecb0843cacc5663ad145c368a0fea2-31836886"></a>
### [api/PowerPoint.Slide.CustomLayout.md](https://github.com/patternplane/VBA-Docs/blob/patch-1/api/PowerPoint.Slide.CustomLayout.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d%5CPullRequest%5C202105270757257898-1380%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EYadoDvxSw%2F2cmEW0JAR1h7BYgltjKCINaC6RxZrHD0%3D&st=2021-05-27T07%3A56%3A17Z&se=2021-06-27T08%3A01%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 18:56 UTC, lindalu-MSFT requested changes
Read/write not read/right

2021-09-17 17:35 UTC, closed without merging