[Bulk] Validation - duplicate alt tags
MicrosoftDocs/VBA-Docs pull request #1608
Opened 2022-07-12 19:13 UTC by vatmicro

This PR fixes 40 duplicate alt tag issues.

2022-07-12 19:45 UTC, opbld31 commented
Docs Build status updates of commit _[c2d90e9](https://github.com/vatmicro/VBA-Docs/commits/c2d90e99b128509160f0696b00f7ed21fadfade8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/.vscode/settings.json](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/.vscode/settings.json) | :white_check_mark:Succeeded | |
[api/Word.Options.MatchFuzzyHF.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyHF.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzyhf?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyKiKu.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyKiKu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzykiku?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyTC.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyTC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzytc?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyZJ.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyZJ.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzyzj?branch=pr-en-us-1608) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d/202207121913297752-1608/BuildReport?accessString=28edbdd2036e320b8a18f57f11d64a5295469fa0b4844fbaa1f80f87b8f87048).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 21:05 UTC, opbld31 commented
Docs Build status updates of commit _[591e4b9](https://github.com/vatmicro/VBA-Docs/commits/591e4b9ae7eb55267af02ea709dc4f10f72df83e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/Word.Options.MatchFuzzyHF.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyHF.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzyhf?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyKiKu.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyKiKu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzykiku?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyTC.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyTC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzytc?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyZJ.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyZJ.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzyzj?branch=pr-en-us-1608) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d/202207122031269255-1608/BuildReport?accessString=9445362b4207001d8c46ea76b49259d45204de560e5aefa1cbcdb6be5ac5bb08).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 21:44 UTC, vatmicro commented
Global effort to fix validation errors

@lindalu-MSFT 
 
The Content & Learning team is fixing build validation errors on docs.microsoft.com. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. I’d very much appreciate your timely review and feedback on these changes I’ve suggested. Thanks!

2022-07-15 00:32 UTC, lindalu-MSFT requested changes
Please change all to "Screenshot of symbol..."

2022-07-21 15:58 UTC, vatmicro commented
Hi @lindalu-MSFT  , I have made the changes that you requested.

2022-07-21 16:32 UTC, opbld33 commented
Docs Build status updates of commit _[01b56d6](https://github.com/vatmicro/VBA-Docs/commits/01b56d68338d8fa8747d3b0d78c76d025c431d4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/Word.Options.MatchFuzzyHF.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyHF.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzyhf?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyKiKu.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyKiKu.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzykiku?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyTC.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyTC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzytc?branch=pr-en-us-1608) |
[api/Word.Options.MatchFuzzyZJ.md](https://github.com/vatmicro/VBA-Docs/blob/712-2/api/Word.Options.MatchFuzzyZJ.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/vba/api/word.options.matchfuzzyzj?branch=pr-en-us-1608) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d/202207211557177804-1608/BuildReport?accessString=a923bc2c704b4e847f7633257a766d91c09ed46d5ac5c1adacbca83d306a6181).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6e765f2a-9c82-bcd6-3a9b-4bbd2d75f74d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 16:44 UTC, lindalu-MSFT approved these changes

2022-07-21 16:44 UTC, merged